name: Create Pull Request (Release-to-Development)
on:
  push:
    branches:
      - Release
jobs:
  productionPromotion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: Development
      - name: Fetch & Reset Release Branch
        run: |
          git fetch origin Release:Release
          git reset --hard Release
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: Release
          # branch-suffix: timestamp
          title: Auto-Merge Release to Development
          labels: automated
          reviewers: ${{ github.actor }}
