name: Create Pull Request (Release-to-Development)
on:
  push:
    branches:
      - Release

jobs:
  auto-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: Development
      #- name: Fetch & Reset Release Branch
      #  run: |
      #    git fetch origin Release:Release
      #    git reset --hard Release
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          base: Development
          branch: Release
          # branch-suffix: timestamp
          title: Auto-Merge Release to Development
          body: |
            Automated Pull Request
            To keep the Development branch up-to-date with the Release branch            
          labels: automated pr
          assignees: ${{ github.actor }}
          reviewers: ${{ github.actor }}
